### ISSUE TITLE
Fatal EOF error

### ISSUE THREAD

**Issue by Shadoyama1** [DavidArthurCole/EggLedger#14]
Doesn't matter which version I run, I get the following error:

`time="2024-07-19T19:57:51-04:00" level=fatal msg=EOF`

Works perfectly fine on a VM, not sure as to why I'm getting this error. I've disabled my anti-virus and firewall entirely and it does not want to work no matter what I do.

**Comment by DavidArthurCole** [comment]
> Doesn't matter which version I run, I get the following error:
> 
> `time="2024-07-19T19:57:51-04:00" level=fatal msg=EOF`
> 
> Works perfectly fine on a VM, not sure as to why I'm getting this error. I've disabled my anti-virus and firewall entirely and it does not want to work no matter what I do.

What OS are you running, and what version, please? Also have you tried running it in a completely new folder, with a freshly downloaded copy, etc.

**Comment by Shadoyama1** [comment]
Windows 10, the past 3 versions have not worked (haven't tested others) and I've tried fresh installs in multiple different folders.

**Comment by DavidArthurCole** [comment]
Looks like there are a sum total of 12 different places that could be fatally erroring out. I've sent you a friend request on Discord, so that I can provide you with a modified binary that should narrow down exactly which is causing the problem.

**Comment by Shadoyama1** [comment]
I don't believe I received the friend request, my username on discord is a little different from here. My discord username is just Shadoyama, or user ID 194140498754142208.

**Comment by DavidArthurCole** [comment]
Thanks to log outputs from a couple of people, it would appear that Lorca is the root cause of this issue.

[Issue open here](https://github.com/zserge/lorca/issues/119)
[PR open here](https://github.com/zserge/lorca/pull/121)

Copying over from that issue

> Just wanted to add I have 1 person seeing this as well on Windows but 15 others not seeing it with the same application. Seems to be persistent for that person. This is just a standard launch with Windows of the exe that launches Lorca with data.

Given I have my own fork of lorca that's already heavily edited, I'm going to do my best to implement the fixes suggested over there, however, given I have been unable as of yet to replicate this issue on my end, and there seems to be no surefire way to get this issue to present, testing that the fix worked may prove to be rather tedious.
